### ISSUE TITLE
index-list的索引点击不够精确

### ISSUE THREAD

**Issue by BuluthLi** [wxp-ui/wxp-ui#17]
老哥，你的组件写的很好，
1.我发现index-list的索引点击不够准确，你可试试用小程序的scroll-into-view试试精准定位
2.index-list里面可以加个slot,方便扩展
这些我自己的项目里面实现了，自己太low,就不贴代码了，你也可以试试这些优化一下

**Comment by singletouch** [comment]
问题1具体是什么样的不准确呢，问题2:该组件写的复杂了一些，目前没有没有好的办法去加slot

**Comment by BuluthLi** [comment]
1.![image](https://user-images.githubusercontent.com/39046050/70310544-dea19780-184a-11ea-9dec-bf310bed8767.png)
点击右侧的索引，左侧定位不准，推荐使用scroll-into-view,
2.
![image](https://user-images.githubusercontent.com/39046050/70310620-0ee93600-184b-11ea-8f71-4e683455dbaa.png),扩展添加其他信息（比如热度城市，历史城市）

**Comment by singletouch** [comment]
这种slot可以根据自己需要增加，这部分跟业务相关太多了.第一个不准我还是不清楚你是怎么不准，我这边都是ok的

**Comment by BuluthLi** [comment]
测试下来，scrollintoview的兼容性好很多额，确实slot业务相关，只是提个建议吧，slot放到组件中，就可以透明，使用的时候可以直接加业务代码，不用动组件了。其实不改动也没啥吧，只是想组件能更好被大家使用
