### ISSUE TITLE
swipe-list这个有支持长列表功能吗？

### ISSUE THREAD

**Issue by phoenix1630** [wxp-ui/wxp-ui#18]
或者有打算加入对长列表的支持吗？

**Comment by singletouch** [comment]
目前没遇到太长的需求呢

**Comment by singletouch** [comment]
需要长列表可以参考 https://developers.weixin.qq.com/miniprogram/dev/extended/component-plus/recycle-view.html

**Comment by phoenix1630** [comment]
刚刚试了swiper-list加官方的cecycle-view混合使用，发现下拉没问题，但是load more有问题，分成了两层，正在痛苦的解决中。。。
