### ISSUE TITLE
scroll 不适配iPhone

### ISSUE THREAD

**Issue by ldc999** [wxp-ui/wxp-ui#2]
用真机iPhone5，scroll 的下拉刷新区域一直显示，安卓正常

**Comment by ldc999** [comment]
> 用真机iPhone5，scroll 的下拉刷新区域一直显示，安卓正常

iPhone ios 12.2  微信版本7.0.3出现这种情况。之后仅将微信升级当前最新的7.0.5，就没有这种现象了，正常使用

**Comment by singletouch** [comment]
嗯, 我看了下 this.createSelectorQuery() 这个方法在组件内使用 2.7.1 及以下的基础库不支持, 我看看有啥替代方法没有, 感谢反馈
