### ISSUE TITLE
movable-area与swpier手势冲突，导致下拉刷新会出现闪烁

### ISSUE THREAD

**Issue by aijun198600** [wxp-ui/wxp-ui#21]
当下拉刷新的时候，在“刷新成功”提示消失的瞬间，按住scroll-view不释放，scroll-view就会出现闪烁现象。
查了下抖动是因为movable-area的change事件返回的y坐标数值出现波动，而波动的时候swiper的catchmove能捕捉到事件（因为不想让swiper进行滚动），基本确定movable-area与swpier存在手势冲突。
请问有好的解决方法吗？

**Comment by singletouch** [comment]
这个确实没什么好的思路呢，不过我试了下iphone上，得刻意这么去做才会出现，一般情况下不会出现呢

**Comment by aijun198600** [comment]
是的，这个应该是微信小程序自己的问题导致的，不刻意去测试的话，不容易复现，对用户体验的影响不大。
