### ISSUE TITLE
拖拽排序(drag)组件的change事件，无法区分是排序中和排序后

### ISSUE THREAD

**Issue by guokai256** [wxp-ui/wxp-ui#22]
当前的change事件无法区分是排序中（touchMove）还是排序后（touchEnd）触发的
建议在当前的change事件中增加属性表明或者增加一个新的事件在touchEnd后触发

**Comment by singletouch** [comment]
只有touchend才会触发

**Comment by guokai256** [comment]
我指的“touchend”是指松手的时候
比如，我把第1个拖动到第4个，然后松手，会依次触发3次change事件（分别是拖动到第2，第3，第4位置时），但其实我只关心最后一次（也就是松手的时候）的change事件，而现在的change事件无法满足

**Comment by singletouch** [comment]
把touchend事件内抛出个事件就好了，我过两天看看给加上去，着急用就自己先整一下
