### ISSUE TITLE
scroll 组件用防抖同步 scroll-top 属性有什么特殊用途嘛

### ISSUE THREAD

**Issue by zhangzhengyi12** [wxp-ui/wxp-ui#23]
我在使用过程中发现受限于 scroll 事件的触发密度，在高速滚动下容易出现回滚的情况(时间大概是一次滚动的末尾，幅度大概10个 px)，原因应该是 scroll 事件最后一次触发时 给的高度 与最终停下来不相等，然后100ms 后触发更新 scroll-top 的函数，接着造成回滚。

我这里直接把整块同步 scroll-top 的部分给删除了，基本没有这种情况了。

看了下变量使用，应该不会造成什么影响。

所以想问问这东西假设没有什么特殊用途的话，是不是可以考虑删除掉，因为对于性能和体验影响都蛮大的

**Comment by singletouch** [comment]
这个主要是解决开发者工具和某些安卓机器滑到底会卡住的情况，参见#5，使用scroll-view做上拉加载应该都会遇到这个问题，但是场景不是太多，如果考虑性能多于兼容可以去除

**Comment by zhangzhengyi12** [comment]
感谢解答！
