### ISSUE TITLE
拖拽排序列表

### ISSUE THREAD

**Issue by lovedaan** [wxp-ui/wxp-ui#26]
你好，请问拖拽排序，当列表超过一屏的高度时候，不能滑动，请问这个要怎么解决呢

**Comment by singletouch** [comment]
应该是可以滑动的

**Comment by lovedaan** [comment]
你好，我是下载你那个uniapp的版本，运行之后在手机上不能滑动，https://ext.dcloud.net.cn/plugin?id=961，可以帮忙看看么

**Comment by singletouch** [comment]
他们 uni-app 的没实现这个功能，而且是我很久之前写的版本了，实在需要 uni 可以根据我的最新代码改一下，也不复杂的换个前缀就好了

**Comment by singletouch** [comment]
https://ext.dcloud.net.cn/plugin?id=929 你试试这个版本好像是可以的
