### ISSUE TITLE
scroll组件的overOnePage

### ISSUE THREAD

**Issue by DJsunshine** [wxp-ui/wxp-ui#28]
当页面中存在条件筛选去下拉刷新的时候 我遇到这样的问题
比如是综合排序  获取到了数据，然后我上滑加载更多后  overOnePage为true
这个时候我把条件改变 综合排序变成 距离远近的话  数据清空后 但是overOnePage为true 一直会显示加载中
![image](https://user-images.githubusercontent.com/24601965/78867611-f5176400-7a73-11ea-8997-ce6e9b4e0841.png)
![image](https://user-images.githubusercontent.com/24601965/78867703-15dfb980-7a74-11ea-991e-1bdb3e3f3c3d.png)

**Comment by singletouch** [comment]
没听懂～

**Comment by DJsunshine** [comment]
{{listCount !== 0 && overOnePage  && (requesting || end)}}" 目前加了这段代码，这个问题目前看解决了 具体情况我加您微信 发您
