### ISSUE TITLE
drag组件使用，请问extraNodes 是不是可以去掉的？

### ISSUE THREAD

**Issue by wenh7788** [wxp-ui/wxp-ui#32]
1.因为正常的情况下 接口返回的数据会告诉你那些数据不可以移动的。（这些是可以根后端商量的）
我看代码中init()方法中 好像就是为了构造一个方便使用的数据结构（list）
2.还有容器的宽高相关计算也可以去掉的。原因是我看到这种计算 我总是会觉得要有什么小细节的适配动作。貌似也没有太大作用呢？
3.如果是跨区域拖拽有没有什么好的思路，谢谢～～

**Comment by singletouch** [comment]
extraNodes 是额外节点,就是可能会有一些不参与排序的节点,但是又要展示的
容器高度肯定要计算的,不然整块区域就没高度了,肯定是会出问题的
跨区,具体看情况,如果是两个地方互相拖拽,就提供一个方法根据pageX和pageY计算当前drag 组件内的元素的索引位置.然后通过组件实例调用该方法得到索引,把需要的元素插入或者删除就好了
最后推荐使用drag-wxs性能会好点, 那个drag组件是老版本的实现

**Comment by wenh7788** [comment]
有个疑问 为什么 你代码中的每个item的 left 和top都是固定的？我用的是flex的布局。所以每个item的left 和top 肯定都不一样。所以我遇到的问题就是长按的时候只有第一个item 可以定位到item的中心 其他的item 都偏了一个left。

**Comment by singletouch** [comment]
这个用的是绝对定位和transform,不能换成flex

**Comment by wenh7788** [comment]
嗯嗯。谢谢了。然后 有一个小小的建议。extraNodes 我个人认为可以不要。我明白您的初衷，尽量让原有的listData和extraNodes不去有任何的牵连。而且您在这个地方做了很多的逻辑处理，比如初始化排序的地方。当然这个可能跟具体的业务逻辑有关啦～～。而且看到您的代码中 有一个fixed的属性，其实完全就可以根据这个字段来去判断固定或是不固定就可以了吧。还有sortKey 其实都可以由后端直接返回的。总结就是有几个关键的属性 fixed sortKey 感觉都是可以直接从原始数据listData来做的。这样可以减少您很多的代码。而且逻辑也清晰一些。最初读代码的时候。extraNodes着实把我绕进去了。因为我们的确也有固定不需要排序的item。愚见愚见～～：）

**Comment by singletouch** [comment]
对的,就是想做的多一点,后面还会做更多.你们不使用可以不关心.主要就是比如图片上传时候有个 '+' 的按钮,这种不参与排序但是又得参与显示的节点,只不过通常 '+' 是在数组最后,我这个做的通用了点,每个节点前后都可以插入不参与排序的节点

**Comment by wenh7788** [comment]
谢谢了～～我关闭了啊～～
