### ISSUE TITLE
大佬你好，我提个建议，也是我目前急需的功能。

### ISSUE THREAD

**Issue by kiccer** [wxp-ui/wxp-ui#35]
可否将 drag 组件拆分成 drag 和 drag-item 两个部分。
然后使用

```html
<drag id="drag"
    bind:click="dragItemClick"
    bind:change="dragOnChange"
    bind:sortend="dragSortEnd"
    bind:scroll="dragOnScroll"
    list-data="{{specList}}"
    columns="{{columns}}"
    scroll-top="{{scrollTop}}">

    <drag-item
        wx:for="{{specList}}"
        data-item="{{item}}"
        data-index="{{index}}">
        <view>
            Content...
        </view>
    </drag-item>
</drag>
```

这样的结构来书写列表项，不是在组件内部遍历，而是在页面中遍历。这样可以在页面中写列表项的样式，而且组件变得复用性更高了。

本来是打算在大佬的组件基础上增加 `slot-scope` 的，结果发现微信官方没有支持 `slot-scope`

所以只好自己尝试着拆代码写成两个关联组件了。

可是我能力有限，很难做到尽善尽美，不知道作者是否有空，可以实现一下这个功能？拜谢~

**Comment by singletouch** [comment]
参考 drag-wxs 使用抽象节点完成分离

**Comment by kiccer** [comment]
厉害了！我去试试看咋用！

**Comment by kiccer** [comment]
`drag-wxs` 的 `item-wrap-class` 属性是什么作用呢？

**Comment by kiccer** [comment]
还有，我发现 `drag-wxs` 在我这里没有自动计算内容高度，容器的高度是0

**Comment by kiccer** [comment]
我找到高度没有自动计算的原因了。
把 `components/drag-wxs/index.wxml` 中的第五行改成 `style="height: {{baseData.rows * baseData.itemHeight}}px"` 就可以了
