### ISSUE TITLE
别的组件都看懂了，但swipe-list是啥

### ISSUE THREAD

**Issue by kero990** [wxp-ui/wxp-ui#37]
组件目录里没有单独的swipe-list，page里倒是有，但是是你写好的例子，而不是单独组件
请问这个是单独组件吗？readme里完全没有写swipe-list的使用方法啊
麻烦问下这个怎么用？不会是用tab和scroll拼出来吧

**Comment by singletouch** [comment]
是的，就是拼出来的多页签 带下拉刷新的页面，因为不太好封装成组件，就直接在页面层面组合了

**Comment by kiradea** [comment]
> 组件目录里没有单独的swipe-list，page里倒是有，但是是你写好的例子，而不是单独组件
> 请问这个是单独组件吗？readme里完全没有写swipe-list的使用方法啊
> 麻烦问下这个怎么用？不会是用tab和scroll拼出来吧

不是，使用movearea 实现的，你看下源码就懂了
