### ISSUE TITLE
上拉加载有时不触发

### ISSUE THREAD

**Issue by iplusx** [wxp-ui/wxp-ui#5]
- 环境
 MacOS 10.14.5 官方微信开发者工具v1.02.1907300
- 问题
上拉加载有时候没有效果，没反应（已经把end写死为false使其能够无限加载）
- 复现
没有找到复现的规律，反复上拉几次（最好缓慢地上拉），肯定会出现的
- 延伸
谷歌搜索「scroll-view bindscrolltolower 触发」发现有很多类似的情况，很多都在说原因是scroll-view没有给出指定高度，导致小程序不确定是否到达底端

请问您知道具体原因并且能够修复吗，谢谢。

**Comment by singletouch** [comment]
这个在真机上应该不会出现, 你可以用真机测试, 电脑上测试时候如果不行用力多拉几次即可. 如果真机也发现问题请告诉我.

**Comment by iplusx** [comment]
真机上也出现的，和微信开发者工具是一样的效果。你把pages/swipe-list/index/index.js:126 改成 pageData.end = false ，多试几次，应该会复现。
还有一点我忘了说了哈，就是出现这种情况的时候，往下拉再上拉，就会加载出来了。真机和开发者工具都是这样的。

**Comment by singletouch** [comment]
什么机型?

**Comment by singletouch** [comment]
我这边测试 iphoneX 没有问题, Mac 上的微信开发者工具有问题, 安卓目前没有测试机器.

问题具体表现为: 有概率不触发 bindscrolltolower 事件.

同理使用 bindscroll 事件去实现触底加载, 同样有大概率不触发事件. 具体实现:

```
scroll(e) {
	console.log(e.detail.scrollTop)
	if(e.detail.scrollTop + scrollView高度 == e.detail.scrollHeight) {
		if (!this.properties.end) {
			this.setData({
				mode: 'more'
			})
			this.triggerEvent('more');
		}
	}
}

```
这里通过打印 scrollTop 的值发现, 在 scroll-view 滑动到底部时 scrollTop 的值并未达到最大, 导致
e.detail.scrollTop + scrollView高度 == e.detail.scrollHeight 等式不成立. 这里可以判断微信自身 bindscrolltolower 事件也是用类似这个条件去触发的. 所以也会有同样的问题.

还有上述的 **往下拉再上拉，就会加载出来了** 这种情况是因为, scroll-view 已经触底了, 继续向下滑动因为已经到底了所以不会触发 scroll 事件自然也就不会触发 bindscrolltolower, 然后表现就是卡住了. 但是往下拉再上拉后会重新触发scroll事件, 并且这种情况 scrollTop 大概率都不会出问题, 可能是滑的慢也可能是滑的距离短, 反正就是能触发. 基本上我上网看了, 这个问题目前好像无解, 只能坐等微信修复了(ps: 建议去微信小程序社区反馈, 目前的反馈看了大部分都没说清楚问题 ). 

这里提供一种不太优的解决方案, 但是至少在不能滑的机器上能滑了:

```
scroll(e) {
	clearTimeout(this.timer)
	this.timer = setTimeout(() => {
		this.setData({
			scrollTop: e.detail.scrollTop
		})
	}, 100)
}
```

具体原理就是设置 scroll-view 的 scrollTop 为最后一次触发 scroll 事件中的 scrollTop. 这样就不会出现看似到底其实没到, 然后不触发事件. 但是有些 scroll 事件失效比较多的时候体验可能就比较差了, 一两次的基本都还好. 还有这里也不会影响正常的机型

**Comment by iplusx** [comment]
感谢解答和回复。之前忙事情忘记回复了，抱歉。我用的真机是安卓的，一加5T。我刚刚拉了最新代码试了下，确实解决了哈 👍 就是还有点小瑕疵，页面会稍微抖动两下，但完全可以接受了。只能说微信官方留的坑～

**Comment by singletouch** [comment]
哈哈, 很多细节还是要更多机器测试
