### ISSUE TITLE
swipe-list 会出现上面tab 无限乱滑动的现象

### ISSUE THREAD

**Issue by shomerchang** [wxp-ui/wxp-ui#6]
在各tab之间 切换速度很快的情况下会出现乱动的现象
有说把bindchange改成bindanimationfinish，但是改过之后还是如此

**Comment by singletouch** [comment]
> 在各tab之间 切换速度很快的情况下会出现乱动的现象
> 有说把bindchange改成bindanimationfinish，但是改过之后还是如此

这个问题是scroll-view本身, 重新设置scrollLeft的时候会迅速结束过渡效果造成的, 暂时也没有什么好的解决办法,

**Comment by shomerchang** [comment]
> > 在各tab之间 切换速度很快的情况下会出现乱动的现象
> > 有说把bindchange改成bindanimationfinish，但是改过之后还是如此
> 
> 这个问题是scroll-view本身, 重新设置scrollLeft的时候会迅速结束过渡效果造成的, 暂时也没有什么好的解决办法, 针对这个我已经做了好多处理, 我的机器(iphoneX)目前快速切换时候效果不是特别抖动, 不知道你的机型和效果是什么样？是卡了一下能切换成功，还是来回一直抖动

不会卡，就是来回抖动，小米和华为的都是这样

**Comment by singletouch** [comment]
> 在各tab之间 切换速度很快的情况下会出现乱动的现象
> 有说把bindchange改成bindanimationfinish，但是改过之后还是如此

我这边环境: 

电脑环境 Mac10.14.6  
手机 Iphone X 系统版本 IOS 12.4.1 
开发者工具 1.02.1907300

经测试:

1.手机和开发这工具均无无限乱滑的现象 .

2.微信开发者工具的真机测试:

这种情况相对来说性能很低, 会出现上述无限乱滑现象, 我这边换成bindanimationfinish 就好很多了, 或者 仍然使用bindchange 在这个事件里加上 `if(e.detail.source != "touch") return; `这个判断, 具体参照 [微信小程序swiper组件](https://developers.weixin.qq.com/miniprogram/dev/component/swiper.html) 的 Bug & Tip

如果可以的话请提供下你这边的测试环境

**Comment by singletouch** [comment]
> > > 在各tab之间 切换速度很快的情况下会出现乱动的现象
> > > 有说把bindchange改成bindanimationfinish，但是改过之后还是如此
> > 
> > 
> > 这个问题是scroll-view本身, 重新设置scrollLeft的时候会迅速结束过渡效果造成的, 暂时也没有什么好的解决办法, 针对这个我已经做了好多处理, 我的机器(iphoneX)目前快速切换时候效果不是特别抖动, 不知道你的机型和效果是什么样？是卡了一下能切换成功，还是来回一直抖动
> 
> 不会卡，就是来回抖动，小米和华为的都是这样

麻烦提供下具体机型, 我好找对应的机器测试, 目前手头只有一台手机

**Comment by shomerchang** [comment]
这边还没上线，是内网。。现在就是用的开发者工具的真机测试，可能就是你说的性能低的原因吧，开发者工具里没有乱滑的现象

**Comment by singletouch** [comment]
哦哦, 那还是建议你换成bindanimationfinish, 怎么说还是这个好点, bindchange 官方自己都说有bug

**Comment by shomerchang** [comment]
> 哦哦, 那还是建议你换成bindanimationfinish, 怎么说还是这个好点, bindchange 官方自己都说有bug

好哒  谢谢啦

**Comment by singletouch** [comment]
> > 哦哦, 那还是建议你换成bindanimationfinish, 怎么说还是这个好点, bindchange 官方自己都说有bug
> 
> 好哒 谢谢啦

还有问题,欢迎反馈.
