### ISSUE TITLE
【需求】tab可以支持预设索引吗？

### ISSUE THREAD

**Issue by iplusx** [wxp-ui/wxp-ui#7]
**问题描述：**
目前的tab好像不支持预设索引呢，我在tab指定「tabCur」和swipe-list指定「categoryCur」，初始化tab的activated项始终是第一个，其他数据如listData都是正确的。

**目标：**
可以指定tab的初始化项索引，如果超出tab的数组长度，则为首项0。

希望老兄有时间看下这个需求哈，十分感谢～

**Comment by singletouch** [comment]
最新提交的版本支持了, 忘了链接提交信息了

**Comment by iplusx** [comment]
功能正常的，但是控制台有报错～

> VM255:1 thirdScriptError
Cannot read property '1' of undefined; [Component] Property Observer Error @ components/tab/index#tacCurChange
TypeError: Cannot read property '1' of undefined

同时我在**components/tab/index.js#scrollByIndex**第一行打印日志 _console.log(tabCur, this.items);_ ，发现始终会打印2行，并且首次进入页面打印的第一行是 _1 undefined_ ，怀疑和上述的报错有关联。

**Comment by singletouch** [comment]
少加了个判断,  第一次进来时候 tabCur 监听触发快于 ready 事件, 所以会报错, 这个时候节点信息还没获取到.
