### ISSUE TITLE
拖拽组件可以水平列表排序吗

### ISSUE THREAD

**Issue by Blizzard-liu** [wxp-ui/wxp-ui#8]

**Comment by Blizzard-liu** [comment]
大佬 在线等哦

**Comment by singletouch** [comment]
好像不行呢, 我过几天拓展下, 最近在修 index-list 的坑

**Comment by singletouch** [comment]
可以具体描述下你的需求么, 因为需要控制的参数还是蛮多的, 所以不知道你需求的场景具体是什么样的

**Comment by Blizzard-liu** [comment]
图片浏览  长按下面的缩略图可以实现放大拖拽排序
![image](https://user-images.githubusercontent.com/20244432/66982899-cc786800-f0e9-11e9-9f54-661cd0ea0816.png)

**Comment by singletouch** [comment]
了解了

**Comment by Blizzard-liu** [comment]
thanks

**Comment by Blizzard-liu** [comment]
大佬 可有思路了  预览的图片限制10张

**Comment by singletouch** [comment]
有点难

**Comment by singletouch** [comment]
主要是横向，滑倒边缘，不好像垂直一样自动滑动一段距离, 如果是那样就必须加个 scroll-view 或者用 css transition, 但是垂直情况的直接调用 wx.pageScrollTo 就好了. 而且横向考虑多行也是个问题, 所以思路混乱～～～

**Comment by Blizzard-liu** [comment]
是啊 我搜遍全网也没看到水平拖拽的  只有竖直的

**Comment by Blizzard-liu** [comment]
这个只有一行 没有多行 而且只有10张照片

**Comment by singletouch** [comment]
因为，横向真的不一样， 横向的时候按照垂直的逻辑来说应该是按照从上到下的顺序来排列每一个初始化的数据, 但按照正常阅读习惯这样是不对的，还是要横向去排列，这个就麻烦了，因为要多定义好多参数，最起码你要规定我一行有几个

**Comment by singletouch** [comment]
要做肯定要做多行的，，一行的搞定了，多行也差不多了

**Comment by Blizzard-liu** [comment]
假如一行只显示4个或5个可以做吗

**Comment by singletouch** [comment]
我在想想吧，你也可以看看源码找找思路

**Comment by singletouch** [comment]
只要是超出屏幕都一样

**Comment by Blizzard-liu** [comment]
ok

**Comment by singletouch** [comment]
问题就在于横屏超出之后，滑到底怎么滚动

**Comment by Blizzard-liu** [comment]
安卓/ios原生应该有类似的组件

**Comment by singletouch** [comment]
微信小程序不好控制滚动，想控制必须加scroll-view，原生肯定可以的

**Comment by singletouch** [comment]
前端写起来太蛋疼了，体验都跟不上

**Comment by Blizzard-liu** [comment]
哎

**Comment by Blizzard-liu** [comment]
https://www.jianshu.com/p/d965c80fe901

大佬 看看这个

**Comment by singletouch** [comment]
拖拽我这个可以的，问题就是超出之后怎么滚，真的爆炸头疼，试了scroll-view， transition，movable-view 体验都很差

**Comment by Blizzard-liu** [comment]
我也吐血了

**Comment by singletouch** [comment]
我再看看，你这个可以降级先弄两排，一排五个将就顶一下～～

**Comment by Blizzard-liu** [comment]
666

**Comment by Blizzard-liu** [comment]
这个加单击事件回调怎么加呢

**Comment by Blizzard-liu** [comment]
![image](https://user-images.githubusercontent.com/20244432/67546517-323ea280-f72f-11e9-9d18-b6cdace3e629.png)
有个bug  往左边拖动到屏幕外面 有很大几率回不来  显示空白了 如图

**Comment by singletouch** [comment]
...拖到屏幕外, 手势事件会断掉

**Comment by Blizzard-liu** [comment]
往其他方向都可以 就是左边会断掉.......

**Comment by singletouch** [comment]
不是很明白, 你是在手机上还是模拟器上测的,   我手机试了下没啥问题

**Comment by Blizzard-liu** [comment]
模拟器 真机没问题  ok  

但是在ios上拖动效果不是很好 很容易重叠在一起回不去

**Comment by singletouch** [comment]
真机？我怎么没遇到过

**Comment by Blizzard-liu** [comment]
真机  ios 的 我再看看

**Comment by singletouch** [comment]
不要搞真机调试, 那玩意卡的很

**Comment by Blizzard-liu** [comment]
不是真机调试  是正常测试  ios比安卓问题多

**Comment by singletouch** [comment]
哦哦，我倒是没遇到过 ios 又啥问题呢， 我这边两台机器测试都还挺好的，不行你加我wx吧，这个issue  快炸了 ～～

**Comment by Blizzard-liu** [comment]
你上班吗  还有时间搞这个

**Comment by singletouch** [comment]
比较闲～～

**Comment by Blizzard-liu** [comment]
你wx多少

**Comment by singletouch** [comment]
a1003367083
