### ISSUE TITLE
拖拽组件 超过屏幕 bind/catch冒泡事件 不使用 overOnePage和滑动条的一些想法

### ISSUE THREAD

**Issue by jawa0919** [wxp-ui/wxp-ui#9]
首先感谢提供的组件
overOnePage 猜测是为了无法在超过单屏幕后，组件无法自身滑动而设置的，原因是bind/catch冒泡事件阻拦。
起初，我将 bind:longpress  catch:touchmove  catch:touchend事件绑定在 info下的一个指示拖拽的图标上，这样，冒泡事件只在一个很小的区域被阻拦，很多区域可以滑动。

但是在某些图片上加入拖拽图示有显得不那么优雅。
琢磨一下，建议将

```
catch:touchmove="touchMove" 
catch:touchend="touchEnd"
```
 改成
```
 catch:touchmove="{{dragging?'touchMove':''}}"
 catch:touchend="{{dragging?'touchMove':''}}"
```
完美解决本身滑动的问题，
在没有开始排序拖拽时，没有阻拦事件，
拖拽时，页面滑动有wx.pageScrollTo滑动拉出。

**Comment by singletouch** [comment]
可以这么玩么，，，我梦寐以求啊，但我怎么记得不行啊，，，赶紧去试试

**Comment by singletouch** [comment]
好像可以呢，激动ing
